services:
  envmodel_gpu:
    profiles: ["miner","gpu"]
#    build: .
    image:  h4ckermike/petals:main
    environment:
      - MAX_DISK_SPACE=${MAX_DISK_SPACE}
      - PUBLIC_NAME=${PUBLIC_NAME}
      - MODEL=${MODEL}
      - INITIAL_PEERS=${INITIAL_PEERS}
      - DEVICE=${DEVICE}
    command: python -m petals.cli.run_server --port 31331  --num_blocks=1  $MODEL  --initial_peers $INITIAL_PEERS  --device=$DEVICE
    # --max_disk_space $MAX_DISK_SPACE
    # --public-name $PUBLIC_NAME
    ports:
      - "31331:31331"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  petals-cache-backbone:
