services:
  backbone:
    profiles: ["backbone"]
    image:  h4ckermike/petals:main
    command: python -m petals.cli.run_dht --host_maddrs /ip4/0.0.0.0/tcp/8008 --identity_path /cache/bootstrap1.id
    volumes:
      - petals-cache-backbone:/cache
    network_mode: host
    ipc: host
    restart: unless-stopped
  envmodel_gpu:
    profiles: ["miner","gpu"]
#    build: .
    image:  h4ckermike/petals:main
    environment:
      - MODEL=${MODEL}
      - INITIAL_PEERS=${INITIAL_PEERS}
      - DEVICE=${DEVICE}
    command: python -m petals.cli.run_server --port 31331  --num_blocks=1  $MODEL  --initial_peers $INITIAL_PEERS  --device=$DEVICE
    ports:
      - "31331:31331"
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  petals-cache-backbone:
