services:
  envmodel_gpu:
    profiles: ["miner","gpu"]
#    build: .
    image:  h4ckermike/petals:main
    environment:
      - MAX_DISK_SPACE=${MAX_DISK_SPACE}
      - PUBLIC_NAME=${PUBLIC_NAME}
      - MODEL=${MODEL}
      - INITIAL_PEERS=${INITIAL_PEERS}
      - DEVICE=${DEVICE}
      - BLOCKS=${BLOCKS}
      - PORT=${PORT}
      - PUBLIC_IP=${PUBLIC_IP}
#      - GOLOG_LOG_LEVEL=debug
      - GOLOG_LOG_LEVEL=info
      - GOLOG_FILE=/opt/cillium/var/log/p2pd_miner.log

    command: python -m petals.cli.run_server  --num_blocks=$BLOCKS  $MODEL  --initial_peers $INITIAL_PEERS  --device=$DEVICE --public_name $PUBLIC_NAME --max_disk_space $MAX_DISK_SPACE --public_ip=${PUBLIC_IP} --port ${PORT} --identity_path /cache/bootstrap1.id
    volumes:
      - petals-cache-backbone:/cache
      - log:/opt/cillium/var/log

    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  petals-cache-backbone:
